on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Run Tests
              run: python -m unittest discover -s tests
            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-github:${{ github.sha }} .
                  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                  docker push ${{ secrets.DOCKER_USERNAME }}/docker-github:${{ github.sha }}
